import { placeholderFabric } from "./placeholderFabric";
import type { FabricSwatch, QuiltProject } from "./types";

function gallery(seed: string, count: number): string[] {
  return Array.from({ length: count }, (_, i) => placeholderFabric(`${seed}-gallery-${i}`));
}

function swatches(seed: string, entries: Omit<FabricSwatch, "image">[]): FabricSwatch[] {
  return entries.map((e, i) => ({ ...e, image: placeholderFabric(`${seed}-swatch-${i}`) }));
}

const raw: Omit<QuiltProject, "coverImage" | "photoGallery" | "fabrics">[] = [
  {
    id: "1",
    slug: "midnight-garden",
    projectName: "Midnight Garden",
    status: "Finished",
    year: "2023",
    dateStarted: "March 2023",
    dateCut: "April 2023",
    dateTopFinished: "July 2023",
    dateFinished: "September 2023",
    quiltType: "Bed quilt, queen",
    dimensions: '92" x 96"',
    patternName: "Garden Trellis",
    patternDesigner: "Jen Kingwell",
    patternSource: "Quiltmania",
    quilterName: "Lorena",
    quiltingDesign: "Custom feather quilting, hand guided",
    mainFabric: "Kona Cotton Solids",
    fabricBrand: "Robert Kaufman",
    fabricDesigner: "—",
    fabricCollection: "Kona Solids",
    batting: "Warm & Natural cotton",
    backing: "Indigo shot cotton",
    binding: "Double-fold, hand stitched",
    techniques: ["Hand Piecing", "Hand Quilting", "English Paper Piecing"],
    projectStory:
      "I started this the winter after we lost the garden to the frost — I wanted something that felt like it was still blooming. Every hexagon is a fabric I'd been saving for a decade, some of it from your grandmother's scrap bin. It took the better part of a year, mostly stitched in the evenings while the news was on. I still find pins in the couch cushions.",
    featured: true,
  },
  {
    id: "2",
    slug: "sunday-porch",
    projectName: "Sunday Porch",
    status: "Finished",
    year: "2022",
    dateStarted: "June 2022",
    dateFinished: "August 2022",
    quiltType: "Lap quilt",
    dimensions: '54" x 60"',
    patternName: "Courthouse Steps",
    patternDesigner: "Traditional",
    patternSource: "Family pattern",
    quilterName: "Lorena",
    mainFabric: "Cotton shirting scraps",
    fabricBrand: "Mixed",
    batting: "Bamboo blend",
    backing: "Cream muslin",
    binding: "Machine bound, scrappy",
    techniques: ["Machine Piecing", "Machine Quilting", "Foundation Piecing"],
    projectStory:
      "Made entirely from your father's old work shirts after he cleared out his closet. I couldn't bear to give them to the donation bin, so I cut them into strips instead. This one lives on the porch swing from May through October.",
    featured: true,
  },
  {
    id: "3",
    slug: "harvest-star",
    projectName: "Harvest Star",
    status: "Finished",
    year: "2021",
    dateStarted: "September 2021",
    dateFinished: "November 2021",
    quiltType: "Wall hanging",
    dimensions: '40" x 40"',
    patternName: "Ohio Star Sampler",
    patternDesigner: "Lorena (original)",
    quilterName: "Lorena",
    mainFabric: "Cotton prints, autumn palette",
    fabricBrand: "Moda",
    fabricCollection: "Farmstead",
    batting: "Wool",
    backing: "Rust gingham",
    binding: "Bias, machine stitched",
    techniques: ["Machine Piecing", "Hand Quilting", "Appliqué"],
    projectStory:
      "Made for the harvest table the year the co-op finally had a good crop. I designed the star layout myself on graph paper — first time I didn't work from someone else's pattern.",
  },
  {
    id: "4",
    slug: "blue-hour",
    projectName: "Blue Hour",
    status: "In Progress",
    year: "2026",
    dateStarted: "January 2026",
    quiltType: "Bed quilt, full",
    dimensions: '80" x 88" (planned)',
    patternName: "Log Cabin, courthouse variation",
    patternDesigner: "Traditional",
    mainFabric: "Indigo-dyed cotton",
    fabricBrand: "Hand-dyed, various",
    batting: "Cotton",
    techniques: ["Machine Piecing", "Hand Quilting"],
    projectStory:
      "Every block uses fabric I dyed myself in the backyard vats last summer — thirty-one shades of blue, one for every day. Still on the design wall, still deciding on the border.",
  },
  {
    id: "5",
    slug: "wedding-ring-for-margaret",
    projectName: "Wedding Ring for Margaret",
    status: "Finished",
    year: "2020",
    dateStarted: "January 2020",
    dateFinished: "May 2020",
    quiltType: "Bed quilt, queen",
    dimensions: '90" x 90"',
    patternName: "Double Wedding Ring",
    patternDesigner: "Traditional",
    patternSource: "Grandmother's pattern pieces",
    quilterName: "Lorena",
    quiltingDesign: "Straight-line, quarter inch from seams",
    mainFabric: "Cotton solids and vintage prints",
    fabricBrand: "Mixed / vintage",
    batting: "Cotton",
    backing: "Ivory sateen",
    binding: "Hand stitched",
    techniques: ["Hand Piecing", "Hand Quilting", "English Paper Piecing"],
    projectStory:
      "Made for my sister's fortieth anniversary, using the actual template pieces our mother cut in 1968. The curves nearly broke me — I unpicked the whole top row twice before it lay flat. Margaret cried when she unwrapped it, and so did I.",
    featured: true,
  },
  {
    id: "6",
    slug: "flying-north",
    projectName: "Flying North",
    status: "Finished",
    year: "2019",
    dateStarted: "October 2019",
    dateFinished: "January 2020",
    quiltType: "Lap quilt",
    dimensions: '50" x 65"',
    patternName: "Flying Geese Migration",
    patternDesigner: "Lorena (original)",
    mainFabric: "Cotton prints, blues and greys",
    fabricBrand: "Art Gallery Fabrics",
    fabricCollection: "Woodland Grove",
    batting: "Wool",
    backing: "Charcoal flannel",
    binding: "Machine bound",
    techniques: ["Paper Piecing", "Machine Quilting"],
    projectStory:
      "Started the week your grandfather passed. I needed something with a lot of small, exacting steps to keep my hands busy. The geese all point north because that's the direction he always said the good weather came from.",
  },
  {
    id: "7",
    slug: "kitchen-window",
    projectName: "Kitchen Window",
    status: "Finished",
    year: "2018",
    dateStarted: "April 2018",
    dateFinished: "June 2018",
    quiltType: "Table runner",
    dimensions: '14" x 48"',
    patternName: "Four Patch Variation",
    patternDesigner: "Traditional",
    mainFabric: "Linen-cotton blend",
    fabricBrand: "Essex",
    batting: "Thin cotton",
    backing: "Natural linen",
    binding: "Machine bound",
    techniques: ["Machine Piecing", "Machine Quilting"],
    projectStory:
      "A quick one, made in a weekend for the kitchen table. Sometimes you need a project that finishes before you lose interest.",
  },
  {
    id: "8",
    slug: "pinwheel-summer",
    projectName: "Pinwheel Summer",
    status: "Finished",
    year: "2017",
    dateStarted: "June 2017",
    dateFinished: "August 2017",
    quiltType: "Crib quilt",
    dimensions: '36" x 42"',
    patternName: "Classic Pinwheel",
    patternDesigner: "Traditional",
    mainFabric: "Cotton prints, primary palette",
    fabricBrand: "Moda",
    fabricCollection: "Bright Side",
    batting: "Cotton",
    backing: "Yellow gingham",
    binding: "Machine bound",
    techniques: ["Machine Piecing", "Machine Quilting"],
    projectStory:
      "Made for the first great-grandbaby. I wanted colors that would still look good in every photograph for the next eighty years, so I kept it simple — just red, yellow, and blue turning in circles.",
  },
  {
    id: "9",
    slug: "diamond-in-the-rough",
    projectName: "Diamond in the Rough",
    status: "UFO",
    year: "2016",
    dateStarted: "March 2016",
    quiltType: "Bed quilt, twin",
    dimensions: '66" x 90" (planned)',
    patternName: "Lone Star, simplified",
    patternDesigner: "Eleanor Burns",
    patternSource: "Quilt in a Day",
    mainFabric: "Cotton solids and batiks",
    fabricBrand: "Mixed",
    batting: "—",
    techniques: ["Machine Piecing", "Foundation Piecing"],
    projectStory:
      "The diamonds never wanted to match up and I put it in the closet in a fit of frustration. Ten years later it's still there. Maybe this is the year.",
    lessonsLearned:
      "Should have starched the bias edges before piecing. Every diamond point taught me a new way to swear quietly.",
  },
  {
    id: "10",
    slug: "first-quilt",
    projectName: "The First One",
    status: "Finished",
    year: "1994",
    dateStarted: "January 1994",
    dateFinished: "December 1994",
    quiltType: "Bed quilt, full",
    dimensions: '76" x 84"',
    patternName: "Simple Nine Patch",
    patternDesigner: "Traditional",
    patternSource: "County fair pamphlet",
    mainFabric: "Cotton calico",
    fabricBrand: "Whatever the fabric store had",
    batting: "Polyester",
    backing: "Floral sheet set",
    binding: "Hand stitched, uneven",
    techniques: ["Hand Piecing", "Hand Quilting"],
    projectStory:
      "My very first quilt, made the year you were born, mostly at 2am while you slept. Every stitch is a little wobbly and I wouldn't change a thing about it.",
    lessonsLearned: "Learned to piece by candlelight during a very long winter and a lot of very short naps.",
    featured: true,
  },
  {
    id: "11",
    slug: "courthouse-quiet",
    projectName: "Courthouse, Quiet",
    status: "Finished",
    year: "2024",
    dateStarted: "February 2024",
    dateFinished: "April 2024",
    quiltType: "Lap quilt",
    dimensions: '52" x 52"',
    patternName: "Courthouse Steps",
    patternDesigner: "Traditional",
    quilterName: "Sent out — Prairie Longarm Co.",
    quiltingDesign: "Edge-to-edge meander",
    mainFabric: "Linen and cotton solids",
    fabricBrand: "Robert Kaufman / Essex",
    batting: "Cotton",
    backing: "Oatmeal linen",
    binding: "Machine bound",
    techniques: ["Machine Piecing", "Machine Quilting"],
    projectStory:
      "Made in the six weeks after retiring, when the house was finally quiet enough to hear the sewing machine think.",
  },
  {
    id: "12",
    slug: "star-for-the-new-house",
    projectName: "Star for the New House",
    status: "Finished",
    year: "2025",
    dateStarted: "May 2025",
    dateFinished: "July 2025",
    quiltType: "Wall hanging",
    dimensions: '36" x 36"',
    patternName: "Friendship Star",
    patternDesigner: "Traditional",
    mainFabric: "Cotton solids, warm palette",
    fabricBrand: "Kona Cotton",
    batting: "Cotton",
    backing: "Terracotta solid",
    binding: "Machine bound",
    techniques: ["Machine Piecing", "Hand Quilting"],
    projectStory:
      "A housewarming gift I made for myself when I moved. Every new house deserves a star over the door, even if it just hangs in the hallway.",
    featured: true,
  },
];

const fabricsBySlug: Record<string, FabricSwatch[]> = {
  "midnight-garden": swatches("midnight-garden", [
    { fabricName: "Firelight", designer: "Alexia Marcelle Abegg", colorway: "Meadow" },
    { fabricName: "Add It Up", designer: "Ruby Star Society", colorway: "Coral" },
    { fabricName: "Kona Cotton Solid", designer: "Robert Kaufman", colorway: "Indigo" },
    { fabricName: "Gingham", designer: "Robert Kaufman", colorway: "Pine" },
    { fabricName: "Meadow Floral", designer: "Rifle Paper Co.", colorway: "Blush" },
  ]),
  "wedding-ring-for-margaret": swatches("wedding-ring-for-margaret", [
    { fabricName: "Vintage Calico", designer: "Unknown / inherited", colorway: "Rose" },
    { fabricName: "Kona Cotton Solid", designer: "Robert Kaufman", colorway: "Ivory" },
  ]),
};

export const mockProjects: QuiltProject[] = raw.map((p) => ({
  ...p,
  coverImage: placeholderFabric(p.id),
  photoGallery: gallery(p.id, 4),
  fabrics: fabricsBySlug[p.slug] ?? [],
}));

export function getMockProjectBySlug(slug: string): QuiltProject | undefined {
  return mockProjects.find((p) => p.slug === slug);
}
